[meta]
title = "Node Transcription Starter"
description = "Get started using Deepgram's Transcription with this Node demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "STT"
language = "JavaScript"
framework = "Node"

[pre-build]
command = "npm install"
message = "Dependencies installed"

[build]
command = "npm run build"
message = "Build completed"

[build.config]
sample = "example.env"
output = ".env"

[post-build]
message = "Run `npm start` to get up and running."
